use deploy over create or update cloudformation commands

diff --git a/infra/samhstn/buildspec.yml b/infra/samhstn/buildspec.yml
--- a/infra/samhstn/buildspec.yml
+++ b/infra/samhstn/buildspec.yml
@@ -23,48 +23,59 @@ phases:
           s3://${S3_CODEBUILD_BUCKET_NAME}/${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}
   post_build:
     commands:
-      - |
-        if ! aws cloudformation describe-stacks --stack-name "samhstn-${ISSUE_NUMBER}-vpc" &>/dev/null; then
-          aws cloudformation create-stack \
-            --stack-name "samhstn-${ISSUE_NUMBER}-vpc" \
-            --template-body file://infra/samhstn/vpc.yml
-        fi
+      - aws cloudformation deploy
+          --stack-name "samhstn-${ISSUE_NUMBER}-vpc"
+          --template-file infra/samhstn/vpc.yml
+          --no-fail-on-empty-changeset
+          # - aws cloudformation deploy
+          #     --stack-name "samhstn-${ISSUE_NUMBER}-nat-gateway"
+          #     --template-file infra/samhstn/nat-gateway.yml
+          #     --no-fail-on-empty-changeset
+          #     --parameter-overrides
+          #       
 
-        aws cloudformation wait stack-create-complete --stack-name "samhstn-${ISSUE_NUMBER}-vpc"
+          # - |
+          #   if ! VPC_STACK_STATUS=$(aws cloudformation describe-stacks --stack-name "samhstn-${ISSUE_NUMBER}-vpc"); then
+          #     aws cloudformation create-stack \
+          #       --stack-name "samhstn-${ISSUE_NUMBER}-vpc" \
+          #       --template-body file://infra/samhstn/vpc.yml
+          #   fi
 
-        if aws cloudformation describe-stacks --stack-name "samhstn-${ISSUE_NUMBER}" &>/dev/null; then
-          UPDATE_ERR=$(aws cloudformation update-stack \
-            --stack-name "samhstn-${ISSUE_NUMBER}" \
-            --template-body file://infra/samhstn/dynamic-build.yml \
-            --parameters \
-              ParameterKey=GithubBranch,ParameterValue=${CODEBUILD_SOURCE_VERSION} \
-              ParameterKey=CodeBuildBucketKey,ParameterValue=${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION} \
-              $(aws cloudformation describe-stacks \
-                --stack-name "samhstn-${ISSUE_NUMBER}-vpc" \
-                --query "Stacks[0].Outputs[*].[join(',', [join('=',['ParameterKey', OutputKey]), join('=',['ParameterValue', OutputValue])])] | join(' ', [])" \
-                --output text) \
-            --capabilities CAPABILITY_IAM 2>&1)
-          if [ $? -eq 0 ]; then
-            aws cloudformation wait stack-update-complete \
-              --stack-name "samhstn-${ISSUE_NUMBER}"
-          elif [[ $UPDATE_ERR =~ "No updates are to be performed" ]]; then
-            echo "No updates are to be performed"
-          else
-            echo "UPDATE_ERR: $UPDATE_ERR"
-            exit 1
-          fi
-        else
-          aws cloudformation create-stack \
-            --stack-name "samhstn-${ISSUE_NUMBER}" \
-            --template-body file://infra/samhstn/dynamic-build.yml \
-            --parameters \
-              ParameterKey=GithubBranch,ParameterValue=${CODEBUILD_SOURCE_VERSION} \
-              ParameterKey=CodeBuildBucketKey,ParameterValue=${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION} \
-              $(aws cloudformation describe-stacks \
-                --stack-name "samhstn-${ISSUE_NUMBER}-vpc" \
-                --query "Stacks[0].Outputs[*].[join(',', [join('=',['ParameterKey', OutputKey]), join('=',['ParameterValue', OutputValue])])] | join(' ', [])" \
-                --output text) \
-            --capabilities CAPABILITY_IAM
-          aws cloudformation wait stack-create-complete \
-            --stack-name "samhstn-${ISSUE_NUMBER}"
-        fi
+          #   aws cloudformation wait stack-create-complete --stack-name "samhstn-${ISSUE_NUMBER}-vpc"
+
+          #   if aws cloudformation describe-stacks --stack-name "samhstn-${ISSUE_NUMBER}" &>/dev/null; then
+          #     UPDATE_ERR=$(aws cloudformation update-stack \
+          #       --stack-name "samhstn-${ISSUE_NUMBER}" \
+          #       --template-body file://infra/samhstn/dynamic-build.yml \
+          #       --parameters \
+          #         ParameterKey=GithubBranch,ParameterValue=${CODEBUILD_SOURCE_VERSION} \
+          #         ParameterKey=CodeBuildBucketKey,ParameterValue=${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION} \
+          #         $(aws cloudformation describe-stacks \
+          #           --stack-name "samhstn-${ISSUE_NUMBER}-vpc" \
+          #           --query "Stacks[0].Outputs[*].[join(',', [join('=',['ParameterKey', OutputKey]), join('=',['ParameterValue', OutputValue])])] | join(' ', [])" \
+          #           --output text) \
+          #       --capabilities CAPABILITY_IAM 2>&1)
+          #     if [ $? -eq 0 ]; then
+          #       aws cloudformation wait stack-update-complete \
+          #         --stack-name "samhstn-${ISSUE_NUMBER}"
+          #     elif [[ $UPDATE_ERR =~ "No updates are to be performed" ]]; then
+          #       echo "No updates are to be performed"
+          #     else
+          #       echo "UPDATE_ERR: $UPDATE_ERR"
+          #       exit 1
+          #     fi
+          #   else
+          #     aws cloudformation create-stack \
+          #       --stack-name "samhstn-${ISSUE_NUMBER}" \
+          #       --template-body file://infra/samhstn/dynamic-build.yml \
+          #       --parameters \
+          #         ParameterKey=GithubBranch,ParameterValue=${CODEBUILD_SOURCE_VERSION} \
+          #         ParameterKey=CodeBuildBucketKey,ParameterValue=${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION} \
+          #         $(aws cloudformation describe-stacks \
+          #           --stack-name "samhstn-${ISSUE_NUMBER}-vpc" \
+          #           --query "Stacks[0].Outputs[*].[join(',', [join('=',['ParameterKey', OutputKey]), join('=',['ParameterValue', OutputValue])])] | join(' ', [])" \
+          #           --output text) \
+          #       --capabilities CAPABILITY_IAM
+          #     aws cloudformation wait stack-create-complete \
+          #       --stack-name "samhstn-${ISSUE_NUMBER}"
+          #   fi
